### ISSUE TITLE
通知推送有误

### ISSUE THREAD

**Issue by kgbaO** [KunCheng-He/hifini-sign-in#3]
大佬，我使用的是 企业微信 APP 通知，可是显示错误:
Exception in thread wecom_app:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/ql/data/scripts/KunCheng-He_hifini-sign-in/notify.py", line 417, in wecom_app
    response = wx.send_mpnews(title, content, media_id, touser)
  File "/ql/data/scripts/KunCheng-He_hifini-sign-in/notify.py", line 459, in send_mpnews
    send_url = f"https://{self.HOST}/cgi-bin/message/send?access_token={self.get_access_token()}"
AttributeError: 'WeCom' object has no attribute 'HOST'

这是什么原因哈？

**Comment by KunCheng-He** [comment]
- 报错提示的文件是 notiry.py ，这个文件用的是通知的，好像是青龙自己提供的通知文件，不是我写的
- 根据报错信息 `AttributeError: 'WeCom' object has no attribute 'HOST'` ，是你没有配置 `HOST` 而导致的，所以你首先需要检查你的配置信息是否正确，如果不会配置，查一下相关教程或者我记得青龙面板在配置页面那里好像提供了参考文档，可以看一下

**Comment by kgbaO** [comment]
搞定了，谢谢大佬了

**Comment by kgbaO** [comment]
多账号(2-3个)的话，如何配置哈？
